/* COMP1168 CRN 46322
 * Lab 7 (Single Table Queries)
 * Instructor Abid Rana
 * Kazuma Sato 100 948 212
 */ 
 
-- 1.
SELECT * FROM EMPLOYEE_T
WHERE EMPLOYEENAME LIKE '%L%' AND EMPLOYEENAME NOT LIKE 'L%';

-- 2.
SELECT * FROM EMPLOYEE_T
WHERE EMPLOYEEDATEHIRED LIKE '99-%';

-- 3.
SELECT * FROM CUSTOMER_T
WHERE CUSTOMERSTATE = 'CA' OR CUSTOMERSTATE = 'WA'
ORDER BY CUSTOMERPOSTALCODE ASC;

-- 4.
SELECT * FROM RAWMATERIAL_T
WHERE MATERIALNAME = 'Cherry' AND THICKNESS = 12 AND WIDTH = 12;

-- 5.
SELECT MATERIALID, MATERIALNAME, MATERIALSTANDARDPRICE, THICKNESS FROM RAWMATERIAL_T
WHERE MATERIALNAME = 'Cherry' OR MATERIALNAME = 'Pine' OR MATERIALNAME = 'Walnut'
ORDER BY MATERIAL ASC, MATERIALSTANDARDPRICE ASC, THICKNESS ASC;

-- 6.

-- 7.
SELECT AVG(PRODUCTSTANDARDPRICE) AS PRODUCTLINEAVERAGE
FROM PRODUCT_T
GROUP BY PRODUCTLINEID;

-- 8.


-- 9.

-- 10.

-- 11. 

-- 12.

-- 13.
-- 14.
-- 15.
-- 16.
-- 17.
-- 18.
-- 19.
-- 20.